### ISSUE TITLE
Request: Assistance/Guidance for setting up XDebug

### ISSUE THREAD

**Issue by in0ni** [jdugan6240/kak-dap#1]
Hello @jdugan6240,

I am wondering if you think it's possible, to get XDebug working with this plugin. I have read the docs, and checked https://github.com/xdebug/vscode-php-debug, which according to https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/ implements DAP.

I checked out the code, but unlike C++/Rust , there is no binary -- but rather .js files. I have tried kak-dbgp for this as well, but it always hangs on scripts, will later add an issue for that.

I am wondering if you feel the vs plugin will be difficult to work with, and if there might be another alternative. Any guidance would help, currently I use VS just for debugging, which I would prefer to keep within Kakoune.

Thanks in advance!

**Comment by jdugan6240** [comment]
Sorry for the late reply - I haven't had much time to work on these projects lately, due to life happening.

I haven't really had a look at the adapter in question, but it being a VS plugin shouldn't be an issue, as long as it doesn't call any VS-specific APIs. You would normally run such a plugin by searching in package.json to find what .js file to run, and calling "node whatever_file.js".

I'm at work at the moment, so I can't give more information right now. I'll look into it when I get home.

**Comment by jdugan6240** [comment]
OK, it seems like this should work. In theory. I don't use PHP, so I can't actually test this, but here's how it would theoretically work:

Where your PHP project is, you need a `.kak-dap.json` file in the root directory of the project. Try something like this for that file:

```
{
  // The binary run to start the debug adapter
  "adapter": "node",
  
  // The arguments to the debug adapter, if any
  "adapter_args": ["/path/to/vscode-php-debug/out/phpDebug.js"],

  // The adapter ID. Needed by some debug adapters.
  "adapterID": "xdebug",
  
  // The arguments sent to the "launch" request
  // This will depend on the debug adapter being used
  "launch_args": {
      "port": 9000
  }
}
```

The specific thing to pass to `adapter_args` will depend on where exactly on your system the [vscode-php-debug](https://github.com/xdebug/vscode-php-debug#installation) plugin is installed. You also need to have XDebug installed, obviously.

Keep in mind that `kak-dap` is still fairly limited, so there may be features you're used to in VSCode that we don't have yet. If this works, though, please let me know and I'll try to add it to the wiki.

**Comment by in0ni** [comment]
Thanks. I fully understand, life happening on this end as well so have not taken a look. Will definitely test it out tonight, and let you know how it goes.

**Comment by in0ni** [comment]
Thanks for the guidance. I'm not looking for many features, just see variables -- I only use OSS for debugging, simple stuff.

I have not had much luck. Initially there was issues due to my terminal and kakoune 'new' alias, fixed that and having the dap-setup-ui is perfect once I can get it running for my own layout.

No matter what I do I cannot get a connection working. I have it working with OSS, and had kak-dbgp connected (but crashed on breakpoints). I mention these as I know the configuration in terms of xdebug/lando works.

I can manually run, and check for the node process:
`node /path/to/phpDebug.js`

when I run dap-start, I never get a process running. Here is my config .kak-dap.json:
```
{
  "adapter": "node",
  "adapter_args": ["${HOME}/.local/bin/php-debug/extension/out/phpDebug.js"],
  "adapterID": "xdebug",
  "launch_args": {
    "port": 9003,
    "pathMappings": { "/app/": "${CUR_DIR}/" }
  }
}
```

Here is the vscode config that works:
```
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            // required for lando
            "pathMappings": { "/app/": "${workspaceRoot}/" }
        },
```

I do not have luck with debugging this, it never creates /tmp/kak-dap.log (but I do see the directory with file containing the breakpoint I set):
`set global dap_cmd "kak-dap -s %val{session} --log /tmp/kak-dap.log -vvvv"`

I can confirm with `:echo %opt{dap_cmd}` that it's properly set

**Comment by jdugan6240** [comment]
Yeah, the file logging functionality is kind of buggy, and TBH I've been seriously considering removing it entirely, as redirecting stdout to a file effectively does the same thing.

Since you're saying that you still see the breakpoints file, though, that seems to be a problem. `kak-dap` is supposed to clean that up as soon as it reads it, so that tells me that maybe `kak-dap` isn't in your PATH. If you look in the debug buffer with `:buffer debug`, you should be able to see if invoking the `kak-dap` binary failed.

**Comment by in0ni** [comment]
Nope, not getting any errors in debug buffer. Is there anything else I might be able to do to try and troubleshoot?

**Comment by jdugan6240** [comment]
Ok. What I'm about to ask you to do is not at all typical `kak-dap` usage, but it should give us some idea of what's going on. Basically, we're going to manually perform the steps that `kak-dap` normally does automatically.

- In Kakoune, set whatever breakpoints you want, and then run `:eval %sh{printf '{ "breakpoints": "%s" }' "$kak_opt_dap_breakpoints_info" > /tmp/kak-dap/${kak_session}_breakpoints }`.
- Also in Kakoune, run `dap-setup-ui`. Afterwards, run `:echo %val{session}` and note the value it returns.
- Still in Kakoune, run `:set-option global dap_running true`.
- In a separate terminal, navigate to the directory containing your .kak-dap.json file and run `kak-dap -s whatever_your_session_was -vvvv`.

The terminal output should give some idea of what's happening.

**Comment by in0ni** [comment]
You were right from the get-go, I did not check the executable properly. I actually didn't even have rust installed, so no binary. After installing, I added it manually to PATH, and now it's working.

I would like to see if I can help with one thing, if it's within my scope. When expanding variables, I would like to see about the cursor not jumping back up to line 1. Could you point me to where I can look into this. If it's not too difficult, I can see about taking care of that and doing a MR.

Might even look into syntax highlighting for the variables.

Thank you!

**Comment by jdugan6240** [comment]
The cursor thing should be easy enough for you to tackle. Basically, there would be two commands to look at in the `kak-dap.kak` file:

- `dap-expand-variable`: This command grabs the variable from the current line and sends it to the `kak-dap` binary for processing. I was thinking setting a new option here indicating the "previous cursor position" would work here.
- `dap-show-variables` - This command takes the variable data passes to it and pastes it into the variables buffer. I would think, after the paste is finished, using the `edit` command here to set the cursor position back to the saved value should achieve the desired result.

I hope this gives a good direction to go for this. I greatly appreciate you offering to fix that!

**Comment by in0ni** [comment]
Hello @jdugan6240,

Just wanted to let you know I have this working locally, and will have a few MRs on minor items that will improve usability. I will create different branches/MR for each request.

I thank you for your time, and hope you find the contributions useful!
